/* ============================================================
   INTERFORGE — PIPELINE TYPES
   Shared across all stages. Flows Prospecting → Smelting → Forge.
   ============================================================ */

/* ── Stage names ─────────────────────────────────────────── */
export type Stage = "prospecting" | "smelting" | "forge";

/* ── Smelt mode ──────────────────────────────────────────── */
export type SmeltMode = "3D" | "SPRITE";

/* ── Pose presets (sprite-sheet mode) ────────────────────── */
export interface PosePreset {
  name:        string;   // unique id, e.g. "walk_front_a"
  label:       string;   // "Walk — Front A"
  direction:   string;   // "front" | "back" | "side"
  prompt_hint: string;
}

export interface PoseLibraryResponse {
  default_sheet: string[];
  presets:       PosePreset[];
}

/* New unified pipeline stages (UI-facing) */
export type PipelineStage =
  | "prospect"
  | "smelt"
  | "forge"
  | "publish";

export type AppView = PipelineStage | "projects" | "devtools";

/* ── Vision types ───────────────────────────────────────── */
export interface VisionCard {
  id: string;
  imageSrc: string | null;
  label: string;
  note: string;
  tags: string[];
  pinned: boolean;
  createdAt: string;
}

export interface VisionFrame {
  id: string;
  imageSrc: string | null;
  caption: string;
  createdAt: string;
}

/* ── Publish modes ──────────────────────────────────────── */
export type PublishMode = "comic" | "sprite" | "tiles" | "export";

/* ── Stage metadata (for header bar) ────────────────────── */
export const STAGE_META: Record<AppView, { title: string; subtitle: string }> = {
  prospect: { title: "Prospect", subtitle: "References, generation & sketch" },
  smelt:    { title: "Pose",     subtitle: "Character poses & sprite frames" },
  forge:    { title: "Forge",    subtitle: "3D mesh pipeline (pinned)" },
  publish:  { title: "Publish",  subtitle: "Comics, sprites, tiles, export" },
  projects: { title: "Projects", subtitle: "Creative vault" },
  devtools: { title: "Dev Tools", subtitle: "Diagnostics & profiling" },
};

/* ── View angles (Smelting) ─────────────────────────────── */
export type ViewAngle = "front" | "front_right" | "right" | "back" | "left" | "front_left";

/* ── Asset types ─────────────────────────────────────────── */
export type AssetType =
  | "concept"
  | "character"
  | "creature"
  | "animal"
  | "weapon"
  | "armor"
  | "shield"
  | "prop"
  | "vehicle"
  | "building"
  | "environment"
  | "tileset"
  | "vfx"
  | "ui"
  | "portrait"
  | "logo"
  | "background";

/* ── Art styles ──────────────────────────────────────────── */
export type ArtStyle =
  | "painterly"
  | "pixel_art"
  | "low_poly"
  | "realistic"
  | "stylized"
  | "sketch"
  | "cel_shaded"
  | "isometric"

/* ── Export formats (Forge) ─────────────────────────────── */
export type ExportFormat = "GLB" | "FBX" | "OBJ";

/* ── Reconstruction path ─────────────────────────────────── */
export type ReconstructionPath = "organic" | "hard_surface" | "none";

/* ============================================================
   STAGE OUTPUT TYPES
   Each stage locks its output and passes it to the next.
   ============================================================ */

/**
 * PROSPECTING OUTPUT
 * Generated by the Prospecting tab when user locks an image.
 * Carries the concept art + all analysis data for Smelting.
 */
/** A LoRA applied to a generation: filename stem + weight. */
export interface LoraSelection {
  file:   string;   // LoRA id/stem (matches GET /api/loras `id`)
  weight: number;
}

export interface ProspectingOutput {
  /* Core image data */
  imagePath: string;           // original generated RGB image
  rgbaPath:  string | null;    // rembg'd RGBA — set by backend (Phase 5)
  svgPath:   string | null;    // vtracer SVG file path — set by backend (Phase 5)
  svgData:   string | null;    // inline SVG content for overlay / conditioning

  /* Pipeline context */
  prompt:    string;
  negPrompt: string;
  seed:      number;
  assetType: AssetType | null;
  artStyle:  ArtStyle  | null;

  /* Auto-selected by rules engine (set by backend in Phase 4) */
  lightingPreset:      string | null;
  reconstructionPath:  ReconstructionPath | null;

  /* Job tracking — used by Smelting to resolve file paths on the backend */
  prospectJobId:      string | null;   // backend job ID from the prospect run
  lockedImageIndex:   number;           // which image from the batch was locked

  /* LoRAs used for this generation — reused by the Pose page for style match */
  loras?: LoraSelection[];
}

/**
 * SMELTING OUTPUT
 * Generated by the Smelting tab when all views are approved + locked.
 * The full 3D data package — feeds directly into the Forge mesh pipeline.
 */
export interface SmeltingOutput {
  /* RGB views — one per angle */
  views: Record<ViewAngle, string>;          // angle → image URL

  /* Depth maps — generated alongside RGB (future phase) */
  depthMaps: Record<ViewAngle, string | null>;

  /* Silhouette masks — rembg RGBA per view */
  masks: Record<ViewAngle, string | null>;

  /* Single backend job ID */
  smeltJobId: string | null;

  /* Which pipeline generated these views */
  smeltMode: SmeltMode;

  /* SPRITE mode: the pose preset names generated (folder keys under smelt/) */
  poses?: string[];

  /* Generation settings used */
  prompt: string;

  /* Carried forward from Prospecting */
  prospectingData: ProspectingOutput | null;
}

/**
 * FORGE OUTPUT
 * Final result after mesh pipeline completes.
 * Points to the exported files + metadata.
 */
export interface ForgeOutput {
  meshPath:    string;                  // path to primary export (GLB/FBX/OBJ)
  lodPaths:    Record<string, string>;  // LOD0 → LOD3 paths
  texturePaths: {
    albedo:    string | null;
    normal:    string | null;
    roughness: string | null;
  };
  exportFormat:  ExportFormat;
  polyCount:     number;
  projectFolder: string;               // project folder root path
  completedAt:   string;               // ISO timestamp
}

/* ============================================================
   PROJECT TYPES
   Expanded project workspace types now live in ./projects.ts.
   pipeline.ts remains focused on stage contracts.
   ============================================================ */

/* ============================================================
   BACKEND STATUS TYPE
   Returned by GET /api/status on the FastAPI sidecar.
   ============================================================ */
export interface BackendStatus {
  overall: "ok" | "degraded";
  backend: { status: "ok" };
  gpu: {
    status:       "ok" | "cpu";
    name:         string;
    vram_total_gb: number;
    vram_free_gb:  number;
  };
  models: {
    status:  "ok" | "missing";
    missing: string[];
  };
}

/* ============================================================
   SSE EVENT TYPES
   Events streamed from backend → frontend during long jobs.
   ============================================================ */
export type SSEEventType =
  | "progress"      // step progress update
  | "step_active"   // a pipeline step started
  | "step_done"     // a pipeline step completed
  | "image_ready"   // prospecting: single image downloaded + ready
  | "svg_ready"     // prospecting: SVG analysis complete
  | "view_ready"    // smelting: single view image ready
  | "mesh_ready"    // forge: mesh export available
  | "log"           // informational log message
  | "done"          // entire job completed
  | "error";        // entire job failed with error code

export interface SSEEvent {
  type:       SSEEventType;
  job_id?:    string;
  step_id?:   string;          // step id (e.g. "build", "decimate")
  message?:   string;          // human-readable status
  description?: string;        // step description
  output?:    string;          // step output (step_done)
  progress?:  number;          // 0.0 – 1.0
  pct?:       number;          // percent complete
  step?:      number;          // current step number
  total?:     number;          // total steps
  code?:      string;          // error code e.g. "ERROR_FORGE_BUILD"
  index?:     number;          // image index (prospecting)
  image_url?: string;          // image URL
  rgba_url?:  string | null;   // RGBA image URL
  raw_path?:  string | null;   // raw file path
  mesh_url?:  string | null;   // mesh URL (forge)
  out_dir?:   string | null;   // output directory (forge done)
  view_angle?: string;         // view angle (smelting)
  data?:      unknown;         // step-specific payload
}
