"""
export.py - mesh export: STL (primary), GLB (game engine), DXF (CAD editing).

STL  - CadQuery output, full precision, Blender import.
GLB  - trimesh export with UV atlas + baked texture, game-engine ready.
DXF  - ezdxf 3D face mesh, importable into Fusion 360 / AutoCAD / Rhino.
"""

import os


# -- STL -----------------------------------------------------------------------

def export_stl(solid, output_path: str, cq, exporters) -> str:
    """Export a CadQuery solid to STL. Returns output_path."""
    exporters.export(cq.Workplane().add(solid), output_path)
    size = os.path.getsize(output_path)
    print(f'[masterforge.export] STL -> {output_path}  ({size:,} bytes)')
    return output_path


# -- GLB -----------------------------------------------------------------------

def export_glb(uv_npz_path: str, texture_path: str,
               output_path: str) -> str:
    """
    Build a trimesh with UV atlas + baked texture and export as GLB.

    The UV data (.npz) must already be generated by unwrap.py.
    The texture PNG must already be baked by texture.py.

    Args:
        uv_npz_path  - path to <stem>_uv.npz
        texture_path - path to <stem>_tex.png
        output_path  - where to write the .glb file

    Returns output_path.
    """
    import trimesh
    import numpy as np
    from PIL import Image

    data     = np.load(uv_npz_path)
    vertices = data['vertices'].astype(np.float64)
    faces    = data['faces'].astype(np.int32)
    uvs      = data['uvs'].astype(np.float64)

    mesh = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)

    # Force smooth normals calculation for game engines
    mesh.fix_normals()
    
    if os.path.isfile(texture_path):
        tex_img  = Image.open(texture_path).convert('RGBA')
        material = trimesh.visual.material.PBRMaterial(
            baseColorTexture=tex_img,
            metallicFactor=0.0,
            roughnessFactor=0.85,
        )
        mesh.visual = trimesh.visual.TextureVisuals(
            uv=uvs,
            material=material,
        )
    else:
        print(f'[masterforge.export] GLB: no texture at {texture_path} - '
              'exporting without material')

    mesh.export(output_path)
    size = os.path.getsize(output_path)
    print(f'[masterforge.export] GLB -> {output_path}  ({size:,} bytes)')
    return output_path


# -- DXF -----------------------------------------------------------------------

def export_dxf(stl_path: str, output_path: str) -> str:
    """
    Export mesh as DXF R2010 with 3DFACE entities.
    Importable into Fusion 360, AutoCAD, Rhino, Blender, FreeCAD.

    Args:
        stl_path    - source STL (trimesh loads it)
        output_path - where to write the .dxf file

    Returns output_path.
    """
    import ezdxf
    import trimesh
    import numpy as np

    mesh     = trimesh.load(stl_path, force='mesh')
    vertices = np.array(mesh.vertices, dtype=np.float64)
    faces    = np.array(mesh.faces,    dtype=np.int32)

    doc = ezdxf.new('R2010')
    doc.header['$INSUNITS'] = 6   # 6 = metres (matches Blender default)
    msp = doc.modelspace()

    for face in faces:
        v0 = vertices[face[0]]
        v1 = vertices[face[1]]
        v2 = vertices[face[2]]
        # DXF 3DFACE is a quad - repeat the third vertex for triangles
        msp.add_3dface([
            (float(v0[0]), float(v0[1]), float(v0[2])),
            (float(v1[0]), float(v1[1]), float(v1[2])),
            (float(v2[0]), float(v2[1]), float(v2[2])),
            (float(v2[0]), float(v2[1]), float(v2[2])),
        ])

    doc.saveas(output_path)
    size = os.path.getsize(output_path)
    print(f'[masterforge.export] DXF -> {output_path}  ({size:,} bytes)')
    return output_path
